name: Deploy Hexo Blog

on: 
  push:
    branches: 
      - master

jobs:
  build:
    name: hexo build & deploy
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
    - uses: actions/setup-node@master
      with:
        node-version: 12.x

    - name: Installation
      run: |
        npm install --no-optional
        npm install -g hexo-cli

    - name: Generate
      run: hexo clean && hexo g

    - name: Deploy
      run: |
        mkdir -p $HOME/.ssh
        touch "$HOME/.ssh/known_hosts"
        
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/.ssh/deploy_key
        chmod 700 $HOME/.ssh
        chmod 600 $HOME/.ssh/deploy_key
        chmod 600 $HOME/.ssh/known_hosts
        eval $(ssh-agent)
        ssh-add $HOME/.ssh/deploy_key
        
        ssh-keyscan 157.245.204.1 > $HOME/.ssh/known_hosts
        
        hexo deploy

